version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
    volumes:
      - ./src:/app/src
      - ../anomaly_detector:/app/models/anomaly_detector
      - ../inside_air_predictor:/app/models/inside_air_predictor
      - ../safeBite_score:/app/models/safeBite_score
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
